[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "warroom-demo"
version = "0.1.0"
description = "demo app"    
dependencies = [
    "mcp>=1.14.0",
    "openrouteservice>=2.3.3",
    "requests==2.31.0",
]
